<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Text */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>

<div class="field<?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA) {
    echo ' textarea';
} ?><?php /* @noEscape */ echo $class ?>">
    <label class="label" for="options_<?php echo $block->escapeHtmlAttr($_option->getId()) ?>_text">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
        <?php /* @noEscape */ echo $block->getFormattedPrice() ?>
    </label>

    <div class="control">
        <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_FIELD) : ?>
            <?php $_textValidate = null;
            if ($_option->getIsRequire()) {
                $_textValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textValidate['maxlength'] = $_option->getMaxCharacters();
            }
			?>
            <input type="text"
                   id="options_<?php echo $block->escapeHtmlAttr($_option->getId()) ?>_text"
                   class="input-text product-custom-option"
                   <?php if (!empty($_textValidate)) {?>
                   data-validate="<?php echo  $block->escapeHtml(json_encode($_textValidate));?>"
                   <?php } ?>
                   name="options[<?php echo $block->escapeHtmlAttr($_option->getId()) ?>]"
				   data-selector="options[<?php echo $block->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?php echo $block->escapeHtml($block->getDefaultValue()) ?>"/>
        <?php elseif ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_AREA) : ?>
            <?php $_textAreaValidate = null;
            if ($_option->getIsRequire()) {
                $_textAreaValidate['required'] = true;
            }
            if ($_option->getMaxCharacters()) {
                $_textAreaValidate['maxlength'] = $_option->getMaxCharacters();
            }
            ?>
            <textarea id="options_<?php echo $block->escapeHtmlAttr($_option->getId()) ?>_text"
                      class="product-custom-option"
                    <?php if (!empty($_textAreaValidate)) {?>
                        data-validate="<?php echo $block->escapeHtml(json_encode($_textAreaValidate));?>"
                    <?php } ?>
                      name="options[<?php echo $block->escapeHtmlAttr($_option->getId()) ?>]"
					  data-selector="options[<?php echo $block->escapeHtmlAttr($_option->getId()) ?>]"
                      rows="5"
                      cols="25"><?php echo $block->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
        <?php if ($_option->getMaxCharacters()) : ?>
            <p class="note note_<?= /* @escapeNotVerified */ $_option->getId() ?>">
                <?= /* @escapeNotVerified */ __('Maximum %1 characters', $_option->getMaxCharacters()) ?>
                <span class="character-counter no-display"></span>
            </p>
        <?php endif; ?>
    </div>
    <?php if ($_option->getMaxCharacters()): ?>
        <script type="text/x-magento-init">
        {
            "[data-selector='options[<?= /* @escapeNotVerified */ $_option->getId() ?>]']": {
                "Magento_Catalog/js/product/remaining-characters": {
                    "maxLength":  "<?= /* @escapeNotVerified */ $_option->getMaxCharacters() ?>",
                    "noteSelector": ".note_<?= /* @escapeNotVerified */ $_option->getId() ?>",
                    "counterSelector": ".note_<?= /* @escapeNotVerified */ $_option->getId() ?> .character-counter"
                }
            }
        }
    </script>
    <?php endif; ?>
</div>
