<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)) : ?>
<div class="filter-current">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?php /* @noEscape */ echo count($_filters); ?>"><?php echo $block->escapeHtml(__('Now Shopping by')) ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter) : ?>
            <li class="item">
                <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                <span class="filter-value"><?php echo $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtmlAttr(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?php echo $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?php echo $block->escapeHtmlAttr(__('Previous')) ?>">
                        <span><?php echo $block->escapeHtml(__('Previous')) ?></span>
                    </a>
                    <a class="action remove"
                       title="<?php echo $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?php echo $block->escapeUrl($clearLinkUrl) ?>">
                        <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                    </a>
                <?php else: ?>
                    <a class="action remove" href="<?php echo $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?php /* @noEscape */ echo $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName;?>">
                        <span><?php echo $block->escapeHtml(__('Remove This Item')) ?></span>
                        <i class="meigee-close"></i>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
