<?php /** @var \Amasty\InstagramFeed\Block\Adminhtml\System\Config\GenerateImages $block */ ?>

<button id="<?= $block->getHtmlId() ?>"
        type="button"
        onclick="window.location.href='<?= $block->escapeUrl($block->getGenerateUrl()) ?>'"
        <?php if ($block->getIsDisabled()): ?>
            disabled
        <?php endif; ?>>
    <?= $block->escapeHtml($block->getButtonLabel()) ?>
</button>
