<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Review\Block\Product\View\ListView $block */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)) :?>
<div class="block review-list accordion-item" id="customer-reviews">
    <div class="block-title accordion-title">
        <strong><?= $block->escapeHtml(__('Customer Comments')) ?></strong>
        <span class="icon-more"><i class="icon-plus meigee-plus"></i><i class="icon-minus meigee-minus"></i></span>
    </div>
    <div class="block-content accordion-content">
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
				<div class="top-block clearfix">
					<div class="customer-rating clearfix">
						<?php if (count($_review->getRatingVotes())) : ?>
							<div class="review-ratings">
							<?php foreach ($_review->getRatingVotes() as $_vote): ?>
								<div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
									<div class="rating-result" title="<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
										<meta content = "1"/>
										<meta content = "100"/>
										<i class="star">&#9733;</i>
										<i class="star">&#9733;</i>
										<i class="star">&#9733;</i>
										<i class="star">&#9733;</i>
										<i class="star">&#9733;</i>
										<span style="width:<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
											<i class="star">&#9733;</i>
											<i class="star">&#9733;</i>
											<i class="star">&#9733;</i>
											<i class="star">&#9733;</i>
											<i class="star">&#9733;</i>
											<span itemprop="ratingValue" class="no-visible"><?= $block->escapeHtml($_vote->getPercent()) ?>%</span>
										</span>
									</div>
									<span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
								</div>
							<?php endforeach; ?>
							</div>
						<?php endif; ?>
					</div>
					<div class="customer-info">
						<div class="icon"><i class="meigee-account"></i></div>
						<div class="info">
							<div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
							<p class="review-author">
								<span class="review-details-label"><?= $block->escapeHtml(__('By'))?></span>
								<strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
							</p>
							<div class="date">
								<i class="meigee-calendar"></i>
								<p class="review-date">
									<time class="review-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($_review->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?></time>
								</p>
							</div>
						</div>
					</div>
				</div>
				<div class="review-box clearfix">
					<div class="review-content" itemprop="description">
						<?php /* @noEscape */ echo nl2br($block->escapeHtml($_review->getDetail())) ?>
					</div>
				</div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif;?>
