<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="block <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>">
    <div class="block-title <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>-title"><strong><?php echo $block->escapeHtml($block->getBlockTitle()); ?></strong></div>
    <div class="block-content <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>-content">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
