<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<div class="block <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>">
    <div class="title <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>", "selectorsToggleClass": "active"}}'>
        <strong><?php echo $block->escapeHtml(__($block->getBlockTitle())); ?></strong>
    </div>
    <div class="content <?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>-content" id="<?php echo $block->escapeHtmlAttr($block->getBlockCss()); ?>">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
