<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()) : ?>

    <?php if ($block->getUseContainer()) : ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()) : ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?php echo $block->escapeHtml(__('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum())) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php echo $block->escapeHtml(__('%1 Item', $block->getTotalNum())) ?>
            <?php else: ?>
                <?php echo $block->escapeHtml(__('%1 Item(s)', $block->getTotalNum())) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1) : ?>
        <nav class="pages">
            <strong class="label pages-label" id="paging-label"><?php echo $block->escapeHtml(__('Page')) ?></strong>
            <ul class="pagination" aria-labelledby="paging-label">
            <?php
            if (!$block->isFirstPage()) : ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : ''; ?>
                    <a class="<?php echo $block->escapeHtmlAttr($text ? 'link ' : 'action ') ?> previous" href="<?php echo $block->escapeUrl($block->getPreviousPageUrl()) ?>" title="<?php echo $block->escapeHtmlAttr($text ? $text : __('Previous')) ?>">
                        <span class="label"><?php echo $block->escapeHtml(__('Page')) ?></span>
                        <i class="meigee-slider-arrow-left"></i>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()) : ?>
                <li class="item active">
                    <a class="page first" href="<?php echo $block->escapeUrl($block->getFirstPageUrl()) ?>">
                        <span class="label"><?php echo $block->escapeHtml(__('Page')) ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()) : ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php echo $block->escapeUrl($block->getPreviousJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)) : ?>
                    <li class="item active">
                        <a class="page" title="" href="javascript:void(0);">
                            <span class="label"><?php echo $block->escapeHtml(__('You\'re currently reading page')) ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php echo $block->escapeUrl($block->getPageUrl($_page)) ?>" class="page">
                            <span class="label"><?php echo $block->escapeHtml(__('Page')) ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()) : ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php echo $block->escapeUrl($block->getNextJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()) : ?>
              <li class="item">
                  <a class="page last" href="<?php echo $block->escapeUrl($block->getLastPageUrl()) ?>">
                      <span class="label"><?php echo $block->escapeHtml(__('Page')) ?></span>
                      <span><?php echo $block->escapeHtml($block->getLastPageNum()) ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()) : ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php /* @noEscape */ echo $text ? 'link ' : 'action '?> next" href="<?php echo $block->escapeUrl($block->getNextPageUrl()) ?>" title="<?php $block->escapeHtmlAttr($text ? $text : __('Next')) ?>">
                        <span class="label"><?php echo $block->escapeHtml(__('Page')) ?></span>
                        <i class="meigee-slider-arrow-right"></i>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </nav>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()) : ?>
        <div class="limiter">
            <strong class="limiter-label"><?php echo $block->escapeHtml(__('Show')) ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options form-control selectpicker">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
                    <option value="<?php echo $block->escapeHtmlAttr($block->getLimitUrl($_key)) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?php /* @escapeNotVerified */ echo $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?php echo $block->escapeHtml(__('per page')) ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()) : ?>
    </div>
    <?php endif ?>

<?php endif ?>
