<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php

/**
*  General template for displaying group of blocks divided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <?php
        $key = array_search('header_links_wrapper', $detailedInfoGroup);
        array_unshift($detailedInfoGroup, $detailedInfoGroup[$key]);
        $detailedInfoGroup = array_unique($detailedInfoGroup);
    ?>
    <div class="sections <?php echo $block->escapeHtmlAttr($groupCss) ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?php echo $block->escapeHtmlAttr($groupCss) ?>-items" data-mage-init='<?php echo $block->escapeHtmlAttr($groupBehavior) ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
				if($name == 'mobile_store_menu'){
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                ?>
                <div class="section-item-content" id="<?php echo $block->escapeHtmlAttr($alias); ?>" data-role="content"><?php /* @noEscape */ echo $html; ?></div>
            <?php
				}
			endforeach;?>
			<?php foreach ($detailedInfoGroup as $name):?>
                <?php
				if($name != 'mobile_store_menu'){
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                ?>
                <div class="section-item-content" id="<?php echo $block->escapeHtmlAttr($alias); ?>" data-role="content"><?php /* @noEscape */ echo $html; ?></div>
            <?php
				}
			endforeach;?>
        </div>
    </div>
<?php endif; ?>
