<?php
	$meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
	
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_default')){
		$sticky_logo = $this->getChildHtml("sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_olivia')){
		$sticky_logo = $this->getChildHtml("header2.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_sophia')){
		$sticky_logo = $this->getChildHtml("header3.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_ava')){
		$sticky_logo = $this->getChildHtml("header4.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_isabella')){
		$sticky_logo = $this->getChildHtml("header5.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_mia')){
		$sticky_logo = $this->getChildHtml("header6.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_emily')){
		$sticky_logo = $this->getChildHtml("header7.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_abigail')){
		$sticky_logo = $this->getChildHtml("header8.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_harper')){
		$sticky_logo = $this->getChildHtml("header9.sticky.logo");
	}
	if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_charlotte')){
		$sticky_logo = $this->getChildHtml("header10.sticky.logo");
	}
	
	
	$sticky_logo_status = $this->getConfig('glam_general/glam_header/sticky_header_logo');
	$sticky_nav = $this->getChildHtml("sticky.catalog.topnav");
	$sticky_nav_status = $this->getConfig('glam_general/glam_header/sticky_header_nav');
	$sticky_search = $this->getChildHtml("stickySearch");
	$sticky_search_status = $this->getConfig('glam_general/glam_header/sticky_header_search');
?>

<div id="sticky-header" class="header">
  <div class="container">
    <div class="left-wrapper">
		<span data-action="toggle-nav" class="action nav-toggle">
			<i class="meigee-nav"></i>
			<span>Menu</span>
		</span>
      <?php echo ($sticky_logo_status ? $sticky_logo : ''); ?> 
    </div>
    <div class="right-wrapper clearfix">
      <?php echo ($sticky_nav_status ? $sticky_nav : ''); ?> 
      <?php echo ($sticky_search_status ? $sticky_search : ''); ?> 
    </div>
  </div>
</div>