<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-list';

    $mode = 'list';

    $image = 'new_products_content_widget_list';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();
    /** @var Magento\Catalog\Helper\Output $_helper */
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

	$lightbox_status = $this->helper('\Meigee\Glam\Helper\GlamGeneral')->getCustomThemeOptionCnf('glam_lightbox', 'lightbox_status');
	$lightbox_widget_status = $this->helper('\Meigee\Glam\Helper\GlamGeneral')->getCustomThemeOptionCnf('glam_lightbox', 'lightbox_home');
    $meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
	$stock_status = $this->helper('\Meigee\Glam\Helper\GlamGeneral')->getCustomThemeOptionCnf('glam_product_listing', 'stock_status');
	$rand = rand(5, 1500);
    $quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
    $quickview_btn = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'quickview_btn');
	$front_helper = $this->helper('\Meigee\Glam\Helper\FrontHelper');
	
	$labels_type = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_type');
	$label_new = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_new');
	$label_sale = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_sale');

    $hoverType = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'hover_type');
    switch ($hoverType) {
        case 'default_hover':
            $hoverType = '1';
        break;
        case 'type2_hover':
            $hoverType = '2';
        break;
        case 'type3_hover':
            $hoverType = '3';
        break;
        break;
        case 'type4_hover':
            $hoverType = '4';
        break;
        break;
        case 'type5_hover':
            $hoverType = '5';
        break;
        default:
            $hoverType = '1';
        break;
    }
    $hoverItems = 0;
    if ($quickview_status && $quickview_btn) {
        $hoverItems ++;
    }
    if ($lightbox_status && $lightbox_widget_status) {
        $hoverItems ++;
    }
    if ($showWishlist) {
        $hoverItems ++;
    }
    if($showCompare) {
        $hoverItems ++;
    }
}


$image_hover_status = $meigee_helper->getCustomThemeOptionCnf('glam_image_hover', 'image_hover_status');
$image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('glam_image_hover', 'image_hover_type');
?>

<?php if ($exist) :?>
    <div class="block widget block-new-products <?php /* @noEscape */ echo $mode; ?>">
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @noEscape */ echo $mode; ?> <?php /* @noEscape */ echo $mode; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?> product-hover-<?php echo $hoverType ?>">
                <ol class="product-items <?php /* @noEscape */ echo $type; ?>">
                    <?php foreach ($items as $_item): ?>
                        <li class="item">
							<div class="product-item-info row">
								<div class="image-wrapper">
									<a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
										<?php 
											$hoverImage = $image_hover_status ? $_item->getHoverImage() : false;
											if ($hoverImage)
											{
												$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
																  ->init($_item, 'hover_image')
																  ->setImageFile($hoverImage)
																  ->getUrl();
												$productImage = $block->getImage($_item, $image, array('data-hover-image'=>$hoverImageUrl));
											}
											else
											{
												$productImage = $block->getImage($_item, $image);
											}
											// echo $block->getImage($_item, $image)->toHtml();
											echo $productImage->toHtml();
										?>
									</a>
									 <?php 
										if($front_helper->isProductNew($_item) || $front_helper->isProductSale($_item) || $front_helper->isProductOnlyLeft($_item)) {
											echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_item) && $front_helper->isProductSale($_item)) || ($front_helper->isProductNew($_item) && $front_helper->isProductOnlyLeft($_item)) ? ' two-items' : '').'">';
												if($front_helper->isProductNew($_item) && $label_new) {
													echo '<span class="label-new">'.__('new').'</span>';
												}
												if($front_helper->isProductOnlyLeft($_item) && $label_sale) {
													echo $front_helper->isProductOnlyLeft($_item);
												} elseif($front_helper->isProductSale($_item) && $label_sale) {
													echo '<span class="label-sale">'.__('sale').'</span>';
												}
											echo '</div>';
										}
									?>
									<?php if (($quickview_btn && $quickview_status) || ($lightbox_status && $lightbox_widget_status) || $showCart || $showWishlist || $showCompare) {?>
										<div class="hover-buttons hover-items-<?php echo $hoverItems ?>">
											<?php if($quickview_btn && $quickview_status) { ?>
												<a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_item->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-quickview"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
											<?php } ?>
											<?php if($lightbox_status && $lightbox_widget_status) { ?>
												<a href="<?php echo $block->getImage($_item, $image)->getImageUrl();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
													<i class="meigee-zoom"></i>
												</a>
											<?php } ?>
											<?php if ($hoverType != 3) : ?>
												<?php if ($showWishlist || $showCompare) : ?>
													<div class="add-to-links<?php echo ($showWishlist && $showCompare) ? ' two-items' : ''; ?>" data-role="add-to-links">
														<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) : ?>
															<a href="#"
															   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
															   class="action towishlist" data-action="add-to-wishlist"
															   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
															</a>
														<?php endif; ?>
														<?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
															<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
															<a href="#" class="action tocompare"
															   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
															   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
																<i class="meigee-compare"></i>
															</a>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											<?php endif; ?>
											<?php if ($hoverType == 1 || $hoverType == 2) : ?>
												<?php if ($showCart) : ?>
													<?php if ($_item->isSaleable()) : ?>
														<?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)) : ?>
															<button class="btn btn-default btn-cart action tocart"
																	data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
																	type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<i class="meigee-cart"></i>
																<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
															</button>
														<?php else: ?>
															<?php
																$postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
															?>
															<button class="btn btn-default btn-cart"
																	data-post='<?php /* @noEscape */ echo $postData; ?>'
																	type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<i class="meigee-cart"></i>
																<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
															</button>
														<?php endif; ?>
													<?php else: ?>
														<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
													<?php endif; ?>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php } ?>
									<?php if (!$_item->getIsSalable()) : ?>
										<div class="sold-out-label">
											<span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
										</div>
									<?php endif; ?>
								</div>
								<div class="product-item-details">
									<h4 class="product-item-name">
										<a title="<?php echo $block->escapeHtmlAttr($_item->getName()) ?>"
										   href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</h4>
									<?php if($stock_status != 4 && $stock_status != 2) {
										if ($_item->getIsSalable()) : ?>
											<div class="stock available"><span><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('In stock')) ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Out of stock')) ?></span></div>
										<?php endif;
									} ?>
									<?php if ($templateType) : ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true)?>
									<?php endif; ?>

									<?php if ($description) : ?>
										<div class="product-item-description">
											<?php /* @noEscape */ echo $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
											<a title="<?php echo $block->escapeHtmlAttr($_item->getName()) ?>"
											   href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
											   class="action more"><?php echo $block->escapeHtml(__('Learn More')) ?></a>
										</div>
									<?php endif; ?>

									<?php if($block->getProductPriceHtml($_item, $type)) { ?>
										<div class="product-action-wrapper">
											<div class="price-action-block<?php echo ($_item->getSpecialPrice() ? ' with-special-price' : ''); ?><?php if (!$_item->isSaleable()): echo ' sold-out-item'; endif; ?>">
												<?php echo str_replace('list', 'list-'.$rand.'-product-'.$_item->getId().'', $block->getProductPriceHtml($_item, $type)); ?>
												<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_item)->toHtml(); ?>                                            
											</div>
											<?php if ($hoverType != 1 && $hoverType != 2) : ?>
												<?php if ($showCart) : ?>
													<?php if ($_item->isSaleable()) : ?>
														<?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)) : ?>
															<button class="btn btn-default btn-cart action tocart"
																	data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
																	type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<i class="meigee-cart"></i>
																<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
															</button>
														<?php else: ?>
															<?php
																$postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
															?>
															<button class="btn btn-default btn-cart"
																	data-post='<?php /* @noEscape */ echo $postData; ?>'
																	type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<i class="meigee-cart"></i>
																<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
															</button>
														<?php endif; ?>
													<?php else: ?>
														<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
													<?php endif; ?>
												<?php endif; ?>
											<?php endif; ?>
											<?php if ($hoverType == 3) : ?>
												<?php if ($showWishlist || $showCompare) : ?>
													<div class="add-to-links<?php echo ($showWishlist && $showCompare) ? ' two-items' : ''; ?>" data-role="add-to-links">
														<?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
															<a href="#"
															   data-post='<?php /* @noEscape */ echo $block->getAddToWishlistParams($_item); ?>'
															   class="action towishlist" data-action="add-to-wishlist"
															   title="<?php echo $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
															</a>
														<?php endif; ?>
														<?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
															<?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
															<a href="#" class="action tocompare"
															   data-post='<?php /* @noEscape */ echo $compareHelper->getPostDataParams($_item);?>'
															   title="<?php echo $block->escapeHtmlAttr(__('Add to Compare')) ?>">
																<i class="meigee-compare"></i>
															</a>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php }?>
								</div>
							</div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
