<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 
 /** @var $block Magento\Catalog\Block\Product\View */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $block->escapeHtmlAttr(__('* Required Fields')) . '"';
}
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?php /* @noEscape */ echo $required; ?>>
	<span class="product-options-title block-title">
		<strong><?php echo __('Options'); ?></strong>
	</span>
    <div class="fieldset" tabindex="0">
        <?php echo $block->getChildHtml('', true);?>
    </div>
</div>
