<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */

$meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
$compare_btn = $meigee_helper->getCustomThemeOptionCnf('versatile_product_listing', 'compare_btn');
?>
<?php if($compare_btn){ ?>
<a href="#"
   class="action tocompare"
   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
   data-post='<?php /* @noEscape */ echo $block->getCompareHelper()->getPostDataParams($block->getProduct()); ?>'
   role="button">
   <i class="meigee-compare"></i>
</a>
<?php } ?>
