<?php
$meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
?>
<?php 
/* Header1 */
if($meigee_helper->getCustomThemeOptionCnf('glam_skins', 'skinheader_default')){ ?>
<div class="header-wrapper">
	<header class="page-header content checkout-header">
		<div class="middle-block">
			<div class="container">
				<div class="row">
					<div class="col-sm-6 left-block">
						<div class="panel header"><a class="action skip contentarea" href="#contentarea"><span>Skip to Content</span></a>
							<?php echo $this->getChildHtml("logo.checkout"); ?>
						</div>
					</div>
					<div class="col-sm-6 hidden-xs right-block">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('glam_checkout_header_custom_block')->toHtml();?>
					</div>
				</div>
			</div>
		</div>
	</header>
</div>
<?php } ?>
