<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="post-list clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <li class="post-holder post-holder-<?php echo $_post->getId() ?>">
                <div class="inner"> 
                    <div class="post-title">
                        <a class="post-item-link"
                           href="<?php echo $_postUrl ?>">
                            <?php echo $_postName; ?>
                        </a>
                    </div>
                    <div class="post-info"> 
                        <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                            <div class="post-categories">
                                <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                                    <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                    <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                                <?php } ?>
                            </div>
                        <?php } ?>
                        <?php if ($_author = $_post->getAuthor()) { ?>
                            <div class="post-author">                                           
                                <span><?php echo $block->escapeHtml($_author->getTitle()) ?></span>
                            </div>
                        <?php } ?>
                    </div>
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <div class="post-ftimg-hld">
                            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                            </a>
                        </div>
                    <?php } ?>
                    <div class="post-description clearfix">
                        <div class="post-text-hld clearfix">
                            <?php echo $block->getShorContent($_post) ?>
                        </div>
                        <a class="post-read-more btn btn-default" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                           <span><?php echo __('Read more') ?></span>
                        </a>
                    </div>
                </div>
            </li>
        <?php } ?>
    </ul>
</div>
<?php } ?>