<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct()
?>
<?php if ($_additional = $block->getAdditionalData()) : ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table table-bordered additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?php echo $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) : ?>
                <tr>
                    <th class="col table-label" scope="row"><?php echo $block->escapeHtml($_data['label']) ?></th>
                    <td class="col data" data-th="<?php echo $block->escapeHtmlAttr($_data['label']) ?>"><?php /* @noEscape */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
