<?php

/**

 * Copyright © 2015 Magento. All rights reserved.

 * See COPYING.txt for license details.

 */



// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis



/**

 * Product description template

 *

 * @var $block \Magento\Catalog\Block\Product\View\Description

 */

?>

<?php /* @noEscape */ echo $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($block->getProduct(), $block->getProduct()->getDescription(), 'description') ?>

