<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see \Magento\Framework\View\Element\Html\Calendar
 */
?>

<script>
require([
    "jquery",
    'jquery-ui-modules/datepicker'
], function($){

//<![CDATA[
    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?php /* @noEscape */ echo $days['wide']?>,
            dayNamesMin: <?php /* @noEscape */ echo $days['abbreviated']?>,
            monthNames: <?php /* @noEscape */ echo $months['wide']?>,
            monthNamesShort: <?php /* @noEscape */ echo $months['abbreviated']?>,
            infoTitle: "<?php  echo $block->escapeJs(__('About the calendar')); ?>",
            firstDay: <?php /* @escapeNotVerified */ echo $firstDay?>,
            closeText: "<?php echo $block->escapeJs(__('Close')); ?>",
            currentText: "<?php echo $block->escapeJs(__('Go Today')); ?>",
            prevText: "<?php echo $block->escapeJs(__('Previous')); ?>",
            nextText: "<?php echo $block->escapeJs(__('Next')); ?>",
            weekHeader: "<?php echo $block->escapeJs(__('WK')); ?>",
            timeText: "<?php echo $block->escapeJs(__('Time')); ?>",
            hourText: "<?php echo $block->escapeJs(__('Hour')); ?>",
            minuteText: "<?php echo $block->escapeJs(__('Minute')); ?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: null,
            buttonImage: null,
            showButtonPanel: true,
            showWeek: true,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false
        }
    });

    enUS = <?php /* @noEscape */ echo $enUS?>; // en_US locale reference
//]]>

});
</script>
