<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty"><div><?php echo $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
	$meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		$grid_columns = $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'grid_columns');
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		$grid_columns = '';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('glam_lightbox', 'lightbox_status');
	$lightbox_listing_status = $meigee_helper->getCustomThemeOptionCnf('glam_lightbox', 'lightbox_listing');
	$product_name = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'product_name');
	$product_price = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'product_price');
	$cart_btn = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'cart_btn');
	$compare_btn = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'compare_btn');
	$wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'wishlist_btn');
	$name_align = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'product_name_aligment');
	$stock_status = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'stock_status');
	$image_hover_status = $meigee_helper->getCustomThemeOptionCnf('glam_image_hover', 'image_hover_status');
	$quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
	$quickview_btn = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'quickview_btn');
    $front_helper = $this->helper('\Meigee\Glam\Helper\FrontHelper');

	$labels_type = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_type');
	$label_new = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_new');
	$label_sale = $meigee_helper->getCustomThemeOptionCnf('glam_labels', 'label_sale');

    $hoverType = $meigee_helper->getCustomThemeOptionCnf('glam_product_listing', 'hover_type');
    switch ($hoverType) {
        case 'default_hover':
            $hoverType = '1';
        break;
        case 'type2_hover':
            $hoverType = '2';
        break;
        case 'type3_hover':
            $hoverType = '3';
        break;
        break;
        case 'type4_hover':
            $hoverType = '4';
        break;
        break;
        case 'type5_hover':
            $hoverType = '5';
        break;
        default:
            $hoverType = '1';
        break;
    }
    $hoverItems = 0;
    if ($quickview_status && $quickview_btn) {
        $hoverItems ++;
    }
    if ($lightbox_status && $lightbox_listing_status) {
        $hoverItems ++;
    }
    if ($wishlist_btn) {
        $hoverItems ++;
    }
    if($compare_btn) {
        $hoverItems ++;
    }

	$image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('glam_image_hover', 'image_hover_type');
?>
    <div class="products wrapper <?php /* @noEscape */ echo $viewMode; ?> products-<?php /* @noEscape */ echo $viewMode .' '. $grid_columns; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?> product-hover-<?php echo $hoverType ?>">
        <ol class="products clearfix list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

			<?php if($viewMode == 'list') { ?>
				 <?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info clearfix" data-container="product-<?= /* @noEscape */ $viewMode ?>">
							<div class="image-wrapper">
								<?php
								$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
								if ($hoverImage)
								{
									$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
													  ->init($_product, 'hover_image')
													  ->setImageFile($hoverImage)
													  ->getUrl();
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>$hoverImageUrl));
								}
								else
								{
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));
								}

								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								} ?>
							   <?php
									if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product)) {
										echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
											if($front_helper->isProductNew($_product) && $label_new) {
												echo '<span class="label-new">'.__('new').'</span>';
											}
											if($front_helper->isProductOnlyLeft($_product) && $label_sale) {
												echo $front_helper->isProductOnlyLeft($_product);
											} elseif($front_helper->isProductSale($_product) && $label_sale) {
												echo '<span class="label-sale">'.__('sale').'</span>';
											}
										echo '</div>';
									}
								?>
								<?php if (($quickview_btn && $quickview_status) || ($lightbox_status && $lightbox_listing_status) || $cart_btn || $compare_btn || $wishlist_btn) { ?>
									<div class="hover-buttons hover-items-<?php echo $hoverItems ?>">
										<?php if($quickview_btn && $quickview_status) { ?>
											<a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-quickview"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
										<?php } ?>
										<?php if($lightbox_status && $lightbox_listing_status) { ?>
											<a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
												<i class="meigee-zoom"></i>
											</a>
										<?php } ?>
										<?php if ($hoverType != 3) : ?>
											<?php if($compare_btn || $wishlist_btn) { ?>
												<div data-role="add-to-links" class="add-to-links<?php echo ($wishlist_btn && $compare_btn) ? ' two-items' : ''; ?>"<?php echo strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : ''; ?>>
													<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
														<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
													<?php endif; ?>
												</div>
											<?php } ?>
										<?php endif; ?>
										<?php if ($hoverType == 1 || $hoverType == 2) : ?>
											<?php if ($_product->isSaleable()) : ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <?php if(!$_product->getReservedForInstallment()){?>
												<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php /* @NoEscape */ echo $block->escapeUrl($postParams['action']); ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
															class="action tocart btn btn-default btn-cart">
														<i class="meigee-cart"></i>
														<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												</form>
                        <?php } ?>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php } ?>

								<?php // Product Image ?>

								<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>

								<?php if (!$_product->isSaleable()) : ?>
									<div class="sold-out-label">
										<span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
									</div>
								<?php endif; ?>

							</div>
							<div class="product details product-item-details">
								<?php if($product_name) {
									$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
									<h4 class="product name product-item-name">
										<a class="product-item-link"
										   href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>">
											<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h4>
								<?php } ?>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<div class="price-availability-block clearfix">
									<?php if($stock_status != 4 && $stock_status != 1) {
										if ($_product->isAvailable()) : ?>
											<div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
										<?php else: ?>
											<div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
										<?php endif;
									} ?>
								</div>
								<div class="product-item-inner">
									 <?php if ($showDescription) : ?>
										<div class="product description product-item-description">
											<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
											<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
											   class="action more"><?php echo $block->escapeHtml(__('Learn More')) ?></a>
										</div>
									<?php endif; ?>

									<div class="swatches-wrapper">
										<?php echo $block->getProductDetailsHtml($_product); ?>
									</div>
									<?php if($product_price) { ?>
										<div class="product-action-wrapper">
											<?php if($product_price) { ?>
												<div class="price-action-block<?php echo ($_product->getSpecialPrice() ? ' with-special-price' : ''); ?><?php if (!$_product->isSaleable()): echo ' sold-out-item'; endif; ?>">
													<?php if($product_price) { ?>
														<?php /* @noEscape */ echo $block->getProductPrice($_product); ?>
														<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
													<?php }?>
												</div>
											<?php }?>
											<?php if ($hoverType != 1 && $hoverType != 2) : ?>
												<?php if ($_product->isSaleable()) : ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                          <?php if(!$_product->getReservedForInstallment()){?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php /* @NoEscape */ echo $block->escapeUrl($postParams['action']); ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																class="action tocart btn btn-default btn-cart">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													</form>
                        <?php } ?>
												<?php else: ?>
													<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
												<?php endif; ?>
											<?php endif; ?>
											<?php if ($hoverType == 3) : ?>
												<?php if($compare_btn || $wishlist_btn) { ?>
													<div data-role="add-to-links" class="add-to-links<?php echo ($wishlist_btn && $compare_btn) ? ' two-items' : ''; ?>"<?php echo strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : ''; ?>>
														<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
															<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
														<?php endif; ?>
													</div>
												<?php } ?>
											<?php endif; ?>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			<?php } else { ?>
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info clearfix" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
							<div class="image-wrapper">
								<?php
								$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
								if ($hoverImage)
								{
									$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
													  ->init($_product, 'hover_image')
													  ->setImageFile($hoverImage)
													  ->getUrl();
									if($_product->getHoverImage()) {
										$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>$hoverImageUrl));
									}
								}
								else
								{
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));
								}

								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								} ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
								<?php
									if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product)) {
										echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
											if($front_helper->isProductNew($_product) && $label_new) {
												echo '<span class="label-new">'.__('new').'</span>';
											}
											if($front_helper->isProductOnlyLeft($_product) && $label_sale) {
												echo $front_helper->isProductOnlyLeft($_product);
											} elseif($front_helper->isProductSale($_product) && $label_sale) {
												echo '<span class="label-sale">'.__('sale').'</span>';
											}
										echo '</div>';
									}
								?>
								<?php if (($quickview_btn && $quickview_status) || ($lightbox_status && $lightbox_listing_status) || $cart_btn || $compare_btn || $wishlist_btn) { ?>
									<div class="hover-buttons hover-items-<?php echo $hoverItems ?>">
										<?php if($quickview_btn && $quickview_status) { ?>
											<a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-quickview"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
										<?php } ?>
										<?php if($lightbox_status && $lightbox_listing_status) { ?>
											<a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
												<i class="meigee-zoom"></i>
											</a>
										<?php } ?>
										<?php if ($hoverType != 3) : ?>
											<?php if($compare_btn || $wishlist_btn) { ?>
												<div data-role="add-to-links" class="add-to-links<?php echo ($compare_btn && $wishlist_btn) ? ' two-items' : ''; ?>"<?php echo strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : ''; ?>>
													<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
														<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
													<?php endif; ?>
												</div>
											<?php } ?>
										<?php endif; ?>
										<?php if ($hoverType == 1 || $hoverType == 2) : ?>
											<?php if ($_product->isSaleable()) : ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <?php if(!$_product->getReservedForInstallment()){?>
												<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php /* @NoEscape */ echo $block->escapeUrl($postParams['action']); ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
															class="action tocart btn btn-default btn-cart">
														<i class="meigee-cart"></i>
														<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												</form>
                        <?php } ?>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php } ?>
								<?php if (!$_product->isSaleable()) : ?>
									<div class="sold-out-label">
										<span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
									</div>
								<?php endif; ?>
							</div>
							<div class="product details product-item-details">
								<div class="swatches-wrapper">
									<?php echo $block->getProductDetailsHtml($_product); ?>
								</div>
								<?php if($product_name) {
									$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
									<h4 class="product name product-item-name <?php // echo $name_align; ?>">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h4>
								<?php }
								if($stock_status != 4 && $stock_status != 2) {
									if ($_product->isAvailable()): ?>
										<div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
								   <?php endif;
								}

									echo $block->getReviewsSummaryHtml($_product, $templateType);
								 ?>
								<div class="product-item-inner">
									 <?php if ($showDescription) :?>
										<div class="product description product-item-description">
											<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
											<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
											   class="action more"><?php echo $block->escapeHtml(__('Learn More')) ?></a>
										</div>
									<?php endif; ?>
								</div>
								<?php if($product_price) { ?>
									<div class="product-action-wrapper">
										<?php if($product_price) { ?>
											<div class="price-action-block<?php echo ($_product->getSpecialPrice() ? ' with-special-price' : ''); ?><?php if (!$_product->isSaleable()): echo ' sold-out-item'; endif; ?>">
												<?php if($product_price ) { ?>
													<?php /* @noEscape */ echo $block->getProductPrice($_product); ?>
													<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
												<?php } ?>
											</div>
										<?php }?>
										<?php if ($hoverType != 1 && $hoverType != 2) : ?>
											<?php if ($_product->isSaleable()) : ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <?php if(!$_product->getReservedForInstallment()){?>
                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php /* @NoEscape */ echo $block->escapeUrl($postParams['action']); ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
															class="action tocart btn btn-default btn-cart">
														<i class="meigee-cart"></i>
														<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												</form>
                      <?php } ?>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
											<?php endif; ?>
										<?php endif; ?>
										<?php if ($hoverType == 3) : ?>
											<?php if($compare_btn || $wishlist_btn){ ?>
												<div data-role="add-to-links" class="add-to-links<?php echo ($wishlist_btn && $compare_btn) ? ' two-items' : ''; ?>"<?php echo strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : ''; ?>>
													<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
														<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
													<?php endif; ?>
												</div>
											<?php } ?>
										<?php endif; ?>
									</div>
								<?php } ?>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			<?php } ?>
        </ol>
    </div>
	<div class="toolbar-bottom">
		<?php echo $block->getToolbarHtml() ?>
		<!-- !!!!tmp -->
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
