<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<a class="aminst-relation-link" href="<?= $block->escapeHtml($block->getProduct()->getProductUrl()); ?>" data-aminst-js="relationLink" title="<?= $block->escapeHtml($block->getProduct()->getName()) ?>">
    <span class="aminst-title"><?= $block->escapeHtml($block->getProduct()->getName()) ?></span>
    <span class="aminst-button"><?= $block->escapeHtml(__('See Details')) ?></span>
</a>
