<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
$meigee_helper = $this->helper('\Meigee\Glam\Helper\GlamGeneral');
$price_status = $meigee_helper->getCustomThemeOptionCnf('glam_topcart', 'price');
$icon_status = $meigee_helper->getCustomThemeOptionCnf('glam_topcart', 'icon');
$text_status = $meigee_helper->getCustomThemeOptionCnf('glam_topcart', 'text');
$counter_status = $meigee_helper->getCustomThemeOptionCnf('glam_topcart', 'counter');
?>
<?php if($icon_status || $text_status) { ?>
	<div data-block="minicart" class="minicart-wrapper <?php if($icon_status): echo 'with-icon'; endif;?>">
		<a class="action showcart title-cart" href="<?php echo $block->escapeUrl($block->getShoppingCartUrl()); ?>"
		   data-bind="scope: 'minicart_content'">
				<span class="counter qty empty"
					  data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading()}, blockLoader: isLoading">
			<!-- <?php // if($icon_status) { ?> -->
				<span class="icon">
					<i class="meigee-cart"></i>
				</span>
			<!-- <?php // } ?> -->
			<?php if($text_status) { ?>
				<span class="cart-right-items">
					<?php if($text_status) { ?>
						<span class="text"><?php /* @escapeNotVerified */ echo __('Cart'); ?></span>
						<?php if($counter_status || $price_status) { ?>
							<span><?php //echo __('-'); ?></span>
						<?php } ?>
					<?php } ?>
					<?php if($counter_status) { ?>
						<span class="counter-number">(<!-- ko text: getCartParam('summary_count') --><!-- /ko -->)</span>
						<span class="counter-label">
						<!-- ko if: getCartParam('summary_count') -->
							<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
							<!-- ko i18n: 'items' --><!-- /ko -->
						<!-- /ko -->
						</span>
					<?php } ?>
					<?php if($counter_status && $price_status) { ?>
						<span class="divider"><?php /* @escapeNotVerified */ echo __('/'); ?></span>
					<?php } ?>
					<?php if($price_status) { ?>
					   <!-- ko if: getCartParam('possible_onepage_checkout') -->
					   <!-- ko foreach: getRegion('subtotalContainer') -->
					   <!-- ko template: getTemplate() --><!-- /ko -->
					   <!-- /ko -->
					   <!-- /ko -->
					<?php } ?>
					   <i class="caret"></i>
				</span>
			<?php } ?>
			</span>
		</a>
		<?php if ($block->getIsNeedToDisplaySideBar()) : ?>
			<div class="block block-minicart"
				 data-role="dropdownDialog"
				 data-mage-init='{"dropdownDialog":{
					"appendTo":"[data-block=minicart]",
					"triggerTarget":".showcart",
					"timeout": "2000",
					"closeOnMouseLeave": true,
					"closeOnEscape": true,
					"triggerClass":"active",
					"parentClass":"active",
					"buttons":[]}}'>
				<div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
					<!-- ko template: getTemplate() --><!-- /ko -->
				</div>
				<?php echo $block->getChildHtml('minicart.addons'); ?>
			</div>
        <?php else: ?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
		<?php endif ?>
		<script>
        	window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
		</script>
		<script type="text/x-magento-init">
		{
			"[data-block='minicart']": {
				"Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
			},
			"*": {
				"Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                    $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
                ) ?>"
			}
		}
		</script>
	</div>
<?php } ?>

