<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<meta property="og:type" content="og:product" />
<meta property="og:title" content="<?php /* @noEscape */ echo $block->stripTags($block->getProduct()->getName()); ?>" />
<meta property="og:image" content="<?php echo $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>" />
<meta property="og:description" content="<?php /* @noEscape */ echo $block->stripTags($block->getProduct()->getShortDescription()); ?>" />
<meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>" />
<?php if ($priceAmount = $block->getProduct()->getPriceInfo()->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)->getAmount()):?>
    <meta property="product:price:amount" content="<?php echo $block->escapeHtmlAttr($priceAmount); ?>"/>
    <?php echo $block->getChildHtml('meta.currency'); ?>
<?php endif;?>
