<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Form $block */
?>
<div class="block review-add accordion-item">
    <div class="accordion-title block-title">
        <strong><?= $block->escapeHtml(__('Post a Review/Comment')) ?></strong>
        <span class="icon-more"><i class="icon-plus meigee-plus"></i><i class="icon-minus meigee-minus"></i></span>
    </div>

<div class="accordion-content block-content">
<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
		<legend class="legend review-legend"><span><?= $block->escapeHtmlAttr(__("Write Your Own Review")); ?></span><br /><span><?= $block->escapeHtmlAttr(__("You're reviewing:")); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend>
        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <fieldset class="field required review-field-ratings">
            <legend class="label"><span><?= $block->escapeHtmlAttr(__('How do you rate this product?')) ?></span></legend><br/>
            <div class="control">
                <div class="nested" id="product-review-table">
                    <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating">
                            <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                    id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                    value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                    class="radio"
                                    data-validate="{ 'rating-required':true}"
                                    aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                <label
                                    class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                    for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
									title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
									id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
									<span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                </label>
                            <?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
							<div class="rating-values"><span><?php echo (ceil($_rating->getPercent()))/20 ?></span>/5</div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
    <?php endif ?>
        <div class="inputs-wrapper">
			<div class="field review-field-nickname required">
				<div class="control">
					<input type="text" name="nickname" id="nickname_field" class="form-control" data-validate="{required:true}" value="<?= $block->escapeHtmlAttr(__('Nickname')) ?>" onblur="if (this.value=='') this.value = '<?= $block->escapeHtmlAttr(__('Nickname')) ?>'" onfocus="if (this.value=='<?= $block->escapeHtmlAttr(__('Nickname')) ?>') this.value = ''" />
				</div>
			</div>
			<div class="field review-field-summary required">
				<div class="control">
					<input type="text" name="title" id="summary_field" class="form-control" data-validate="{required:true}" value="<?= $block->escapeHtmlAttr(__('Summary')) ?>" onblur="if (this.value=='') this.value = '<?= $block->escapeHtmlAttr(__('Summary')) ?>'" onfocus="if (this.value=='<?= $block->escapeHtmlAttr(__('Summary')) ?>') this.value = ''" />
				</div>
			</div>
	   </div>
        <div class="field review-field-text required">
            <div class="control">
                <textarea name="detail" id="review_field" class="form-control" cols="5" rows="3" data-validate="{required:true}" onblur="if (this.value=='') this.value = '<?= $block->escapeHtmlAttr(__('Review')) ?>'" onfocus="if (this.value=='<?= $block->escapeHtmlAttr(__('Review')) ?>') this.value = ''"><?= $block->escapeHtmlAttr(__('Review')) ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit btn btn-default"><span><?= $block->escapeHtmlAttr(__('Submit Review')) ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {}
    }
}
</script>
<script type="text/javascript">
require(['jquery'], function ($){
	$('#maincontent').on('click', 'label', function(){
		if($(this).attr('class').indexOf('rating-') != -1){
			star = $(this).attr('class').slice(7);
			$(this).parent().next('.rating-values').find('span').html(star);
		}
	});
});
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtmlAttr(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
